version: "3"
services:
  falcon-api:
    build: falcon-api/.
    container_name: falcon-api
    links:
      - db
    depends_on:
      - db
    env_file:
      - falcon-api/.env
    ports:
      - 5000:5000
  db:
    image: postgres
    container_name: pd_db

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=api_frameworks
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    nginx:
      image: nginx:latest
      container_name: docker-nginx
      restart: always
      ports:
        - "80:80"
