[package]
name = "actix-web"
version = "0.1.0"
authors = ["Usman Haider <uhaider.bese15seecs@seecs.edu.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.7"
serde = "1.0.101"
diesel = "1.4.2"
